### ISSUE TITLE
RSS Feed is Broken

### ISSUE THREAD

**Issue by jon49** [andrewgremlich/blogs#1]
When you switched to providing multiple RSS feeds of different types. You broke the original RSS feed. Also, you made it so the RSS feeds are no longer auto-discoverable by feed readers. Normally you can just paste in the website itself for into the feed reader and it will search for `/index.xml` (don't quote me on that but I think that is what your original feed was). But if that is not there it no longer knows what to do.

**Comment by andrewgremlich** [comment]
How about now?

https://github.com/andrewgremlich/blogs/commit/2132c25f89118dc9080daf13f529f29eb1deb035

https://gremlich.dev/index.xml

**Comment by jon49** [comment]
![rss-not-find](https://user-images.githubusercontent.com/3173098/147616898-0096e348-adfd-42e4-91e8-d993f26197e2.PNG)

Above is what it looks like when I paste in your URL. It should auto find it.

Below is what your old blog RSS referenced.

![rss-old](https://user-images.githubusercontent.com/3173098/147616927-acae40c4-f4bd-416f-8dc0-252dd15497c3.PNG)

So, maybe if we give it a day or two Feedly will recognize it again after it refreshes?

**Comment by jon49** [comment]
If I do paste the whole URL in the Feedly it does work. But it should work automatically to discover it. Maybe there is something else we are missing?

**Comment by andrewgremlich** [comment]
The RSS feeds need to be included in the HTML. It should work with auto detection now.

https://github.com/andrewgremlich/blogs/commit/fa5615b9aafc3160c9919e9766ce2ff9843d1e4d

**Comment by jon49** [comment]
Oh, yes, I see. That's cool. I went to test it but it looks like you haven't updated your website as that line isn't in the page.

**Comment by andrewgremlich** [comment]
Umm it's there.

**Comment by andrewgremlich** [comment]
I tested the autodetect with a different RSS feed. As far as I know this is all fixed and I'll close this.

**Comment by jon49** [comment]
I was looking at the website <https://gremlich.dev/> and am viewing the view source and did a search for `link` and there are 4 links all referencing `css` files but no `link` referencing the `rss` feed. I did a hard refresh too, to bust any caching and it still isn't there.

But, yes, once that it added it does work. Unfortunately, it hasn't been updated for at least this website <https://gremlich.dev/>. I didn't check your others.

**Comment by andrewgremlich** [comment]
That part with RSS being added must be dynamic with React. Instead of viewing page source, open up the dev tools and search in the elements tab. It appears there.

**Comment by jon49** [comment]
Oh, that explains why Feedly isn't finding it. Feedly isn't running the JavaScript to find those tags - it is looking for those tags in the delivered HTML, but since they are dynamic it isn't found.
